apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: pipeline
  name: pipeline
  namespace: default
spec:
  selector:
    matchLabels:
      app: pipeline
  template:
    metadata:
      labels:
        app: pipeline
    spec:
      containers:
      - image: gcr.io/cruzada-nacional/pipeline:ddd60b9c001ecb64178f5d35fb474e22d4dfbccf
        name: pipeline
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
